<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>13.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <WarningsAsErrors>$(WarningsAsErrors);nullable</WarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <IsAotCompatible Condition="!$(MSBuildProjectName.EndsWith('.Tests'))">true</IsAotCompatible>
    <IsTrimmable Condition="!$(MSBuildProjectName.EndsWith('.Tests'))">true</IsTrimmable>
  </PropertyGroup>
</Project>
