<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DotReticulum.Core\DotReticulum.Core.csproj" />
    <ProjectReference Include="..\DotReticulum.Transport\DotReticulum.Transport.csproj" />
    <ProjectReference Include="..\DotReticulum.Interfaces\DotReticulum.Interfaces.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
