using System.Security.Cryptography;
using System.Text;

namespace DotReticulum.Core.Tests;

public class DestinationTests
{
    // Generated by genuine upstream Destination.hash() at revision
    // e40191b3d193b46b7f2d8a44424a594cd758839b; see GenerateUpstreamVectors.py.
    [Theory]
    [InlineData("example.echo", "", "0bcbedcb71b1f0dc873c05b76c2b0dd1")]
    [InlineData("example.echo", "000102030405060708090a0b0c0d0e0f", "e500a759ea178cfe4b4e67ddb0d452e0")]
    [InlineData("应用.回声", "", "74bfe4d520bb0cb8b82f72424e869bcb")]
    [InlineData("应用.回声", "000102030405060708090a0b0c0d0e0f", "03acc6986496af7613f246ad34bcbcb9")]
    public void MatchesUpstreamDestinationHash(string name, string identityHex, string expectedHex)
    {
        var expected = Convert.FromHexString(expectedHex);
        var identity = Convert.FromHexString(identityHex);
        Assert.Equal(expected, Destination.CalculateHash(name, identity));
        var type = identity.Length == 0 ? DestinationType.Plain : DestinationType.Single;
        Assert.Equal(expected, Destination.CalculateHash(name, type, identity));
        Assert.Equal(SHA256.HashData(Encoding.UTF8.GetBytes(name))[..10], Destination.CalculateNameHash(name));
    }

    [Theory]
    [InlineData(DestinationType.Single)]
    [InlineData(DestinationType.Group)]
    [InlineData(DestinationType.Link)]
    public void NonPlainHashUsesBinaryIdentityNotItsDisplayHex(DestinationType type)
    {
        var identity = Convert.FromHexString("000102030405060708090a0b0c0d0e0f");
        Assert.Equal(Convert.FromHexString("e500a759ea178cfe4b4e67ddb0d452e0"),
            Destination.CalculateHash("example.echo", type, identity));
        Assert.NotEqual(Destination.CalculateHash("example.echo." + Convert.ToHexString(identity).ToLowerInvariant()),
            Destination.CalculateHash("example.echo", type, identity));
        Assert.Throws<ArgumentException>(() => Destination.CalculateHash("example.echo", type));
    }

    [Fact]
    public void ValidatesIdentityAndDestinationType()
    {
        foreach (var length in new[] { 1, 10, 15, 17, 32 })
            Assert.Throws<ArgumentException>(() => Destination.CalculateHash("example.echo", new byte[length]));
        Assert.Throws<ArgumentException>(() => Destination.CalculateHash("example.echo", DestinationType.Plain, new byte[16]));
        Assert.Throws<ArgumentOutOfRangeException>(() => Destination.CalculateHash("example.echo", (DestinationType)4));
        Assert.Throws<ArgumentNullException>(() => Destination.CalculateHash(null!));
        Assert.Throws<EncoderFallbackException>(() => Destination.CalculateHash("\ud800"));
    }

    [Fact]
    public void BuildsNamesUsingAppAndAspectsOnly()
    {
        Assert.Equal("example.echo.message", Destination.ExpandName("example", "echo", "message"));
        Assert.Equal("应用.回声", Destination.ExpandName("应用", "回声"));
        Assert.Equal("example", Destination.ExpandName("example"));
        Assert.Throws<ArgumentException>(() => Destination.ExpandName("example.app"));
        Assert.Throws<ArgumentException>(() => Destination.ExpandName("example", "echo.message"));
        Assert.Throws<ArgumentNullException>(() => Destination.ExpandName(null!));
        Assert.Throws<ArgumentNullException>(() => Destination.ExpandName("example", null!));
        Assert.Throws<ArgumentNullException>(() => Destination.ExpandName("example", new string[] { null! }));
    }
}
